name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
  
       runs-on: ubuntu-latest aws
        steps: 
    - name:  tarefa de arquivos
      run: aws ecs describe-task-definition --task-definition tarefa_api --query taskDefinition > task-definition.json
      
